In [1]:
import pandas as pd

In [2]:
corp_equi_wind = pd.read_csv('./corp_equi_wind/en_iate_f1.csv').rename(columns={'Unnamed: 0':'Patterns'})
cols = ['ann_xlnet_htfl.pkl', 'ann_xlnet_wind.pkl',
       'ann_xlnet_equi.pkl', 'ann_xlnet_corp.pkl', 'nes_xlnet_htfl.pkl',
       'nes_xlnet_wind.pkl', 'nes_xlnet_equi.pkl', 'nes_xlnet_corp.pkl']
for col in cols:
    corp_equi_wind['percent_'+col] = round(corp_equi_wind[col]*100/corp_equi_wind[col].iloc[0],2)

In [3]:
corp_equi_wind_df = corp_equi_wind.filter(regex='percent_|Patterns')
corp_equi_wind_df

,Patterns,percent_ann_xlnet_htfl.pkl,percent_ann_xlnet_wind.pkl,percent_ann_xlnet_equi.pkl,percent_ann_xlnet_corp.pkl,percent_nes_xlnet_htfl.pkl,percent_nes_xlnet_wind.pkl,percent_nes_xlnet_equi.pkl,percent_nes_xlnet_corp.pkl
0,NON_PATTERN_F1,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00
1,ADJ_NOUN_F1,105.35,98.23,90.07,97.42,102.65,98.19,91.88,98.73
2,NOUN_NOUN_F1,97.88,82.73,89.17,87.95,95.42,87.00,91.82,90.08
3,ADJ_ADJ_NOUN_F1,101.39,99.29,98.85,98.67,100.73,99.58,99.15,99.36
4,ADJ_NOUN_NOUN_F1,99.60,98.38,99.02,99.43,99.50,99.26,99.39,99.58
5,NOUN_ADJ_NOUN_F1,100.08,99.27,99.36,99.23,99.85,99.43,99.49,99.50
6,NOUN_NOUN_NOUN_F1,100.20,98.50,99.28,99.37,99.87,98.97,99.59,99.56
7,NOUN_ADP_NOUN_F1,96.92,95.59,95.26,94.17,97.27,97.55,95.67,95.53
8,NOUN_ADP_ADJ_NOUN_F1,98.95,98.25,98.69,98.18,99.20,98.95,98.97,98.65
9,ADJ_NOUN_ADP_NOUN_F1,99.26,99.14,99.44,98.81,99.50,99.58,99.35,99.34
10,NOUN_ADP_NOUN_NOUN_F1,98.92,98.57,99.44,98.67,99.17,99.15,99.49,99.34
11,ADJ_NOUN_ADP_ADJ_NOUN_F1,99.66,99.64,99.78,99.78,99.87,99.89,99.92,99.64
12,ADV_ADJ_NOUN_F1,99.75,99.34,98.89,99.56,99.87,99.50,99.15,99.62
13,NOUN_PRON_F1,100.17,98.32,99.12,99.78,100.25,98.84,99.72,99.86
14,ADJ_NOUN_ADJ_NOUN_F1,100.00,99.93,99.96,99.90,100.10,100.00,99.98,100.00

In [13]:
corp_equi = pd.read_csv('./corp_equi/en_iate_f1.csv').rename(columns={'Unnamed: 0':'Patterns'})
corp_equi = corp_equi[corp_equi['Patterns'].str.endswith('_F1')]
for col in cols:
    corp_equi['percent_'+col] = round(corp_equi[col]*100/corp_equi[col].iloc[0],2)
corp_equi_df = corp_equi.filter(regex='percent_|Patterns')
corp_equi_df

,Patterns,percent_ann_xlnet_htfl.pkl,percent_ann_xlnet_wind.pkl,percent_ann_xlnet_equi.pkl,percent_ann_xlnet_corp.pkl,percent_nes_xlnet_htfl.pkl,percent_nes_xlnet_wind.pkl,percent_nes_xlnet_equi.pkl,percent_nes_xlnet_corp.pkl
2,NON_PATTERN_F1,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00
5,ADJ_NOUN_F1,105.82,102.82,91.48,97.37,103.71,100.65,92.39,101.21
8,NOUN_NOUN_F1,106.77,124.91,90.83,89.56,98.98,111.76,93.13,92.65
11,ADJ_ADJ_NOUN_F1,101.52,99.61,98.93,99.32,101.02,99.76,99.15,99.60
14,ADJ_NOUN_NOUN_F1,100.74,102.13,99.25,99.51,99.14,100.96,99.23,99.60
17,NOUN_ADJ_NOUN_F1,100.17,99.87,99.52,99.47,99.87,99.90,99.60,99.47
20,NOUN_NOUN_NOUN_F1,99.66,102.60,99.46,99.81,99.92,100.27,99.60,99.72
23,NOUN_ADP_NOUN_F1,96.85,97.79,95.65,94.72,96.64,97.88,96.09,96.32
26,NOUN_ADP_ADJ_NOUN_F1,99.22,99.09,98.85,98.44,99.08,99.21,98.93,98.32
29,ADJ_NOUN_ADP_NOUN_F1,99.26,99.18,99.71,99.21,99.24,99.76,99.56,99.30
32,NOUN_ADP_NOUN_NOUN_F1,98.88,98.96,99.44,99.04,98.83,99.15,99.42,99.09
35,ADJ_NOUN_ADP_ADJ_NOUN_F1,99.76,99.83,99.90,99.76,99.69,99.90,99.80,99.66
38,ADV_ADJ_NOUN_F1,99.76,99.48,99.12,99.53,99.75,99.66,99.05,99.57
41,NOUN_PRON_F1,99.83,98.44,99.44,99.59,99.90,99.01,99.64,99.85
44,ADJ_NOUN_ADJ_NOUN_F1,100.00,100.00,99.96,99.89,99.97,100.00,99.98,100.00

In [14]:
# corp_equi_df.to_csv('./corp_equi/en_iate_f1_.csv')

In [15]:
# corp_equi_df[(corp_equi_df.filter(regex='percent_').values > 100).any(axis=1)]

In [16]:
# corp_equi_df.filter(regex='Patterns|wind|htfl')

In [17]:
corp_wind = pd.read_csv('./corp_wind/en_iate_f1.csv').rename(columns={'Unnamed: 0':'Patterns'})
corp_wind = corp_wind[corp_wind['Patterns'].str.endswith('_F1')]
for col in cols:
    corp_wind['percent_'+col] = round(corp_wind[col]*100/corp_wind[col].iloc[0],2)
corp_wind_df = corp_wind.filter(regex='percent_|Patterns')
corp_wind_df

,Patterns,percent_ann_xlnet_htfl.pkl,percent_ann_xlnet_wind.pkl,percent_ann_xlnet_equi.pkl,percent_ann_xlnet_corp.pkl,percent_nes_xlnet_htfl.pkl,percent_nes_xlnet_wind.pkl,percent_nes_xlnet_equi.pkl,percent_nes_xlnet_corp.pkl
0,NON_PATTERN_F1,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00
1,ADJ_NOUN_F1,104.65,98.11,96.61,97.18,102.49,98.92,97.59,99.45
2,NOUN_NOUN_F1,96.55,82.34,94.05,89.20,97.17,88.78,94.81,91.51
3,ADJ_ADJ_NOUN_F1,101.01,99.47,99.63,99.11,100.54,99.31,99.75,99.07
4,ADJ_NOUN_NOUN_F1,99.35,98.96,99.40,99.37,99.68,98.75,99.43,99.43
5,NOUN_ADJ_NOUN_F1,100.11,99.28,99.80,99.41,99.95,99.31,99.75,99.55
6,NOUN_NOUN_NOUN_F1,99.95,99.45,99.77,99.59,100.32,99.31,99.88,99.75
7,NOUN_ADP_NOUN_F1,97.09,96.21,97.82,95.64,97.29,97.18,98.01,96.22
8,NOUN_ADP_ADJ_NOUN_F1,99.10,98.41,99.43,98.54,99.24,98.70,99.46,98.71
9,ADJ_NOUN_ADP_NOUN_F1,99.29,99.17,100.00,98.89,99.48,99.57,99.90,99.19
10,NOUN_ADP_NOUN_NOUN_F1,99.10,98.55,99.63,98.93,99.24,98.84,99.78,99.09
11,ADJ_NOUN_ADP_ADJ_NOUN_F1,99.76,99.65,99.91,99.82,99.85,99.69,99.90,99.89
12,ADV_ADJ_NOUN_F1,99.67,99.35,99.51,99.55,99.83,99.51,99.36,99.66
13,NOUN_PRON_F1,100.22,98.31,99.40,99.78,100.20,98.95,99.70,99.81
14,ADJ_NOUN_ADJ_NOUN_F1,99.97,99.98,99.97,99.96,100.05,99.93,99.98,99.96

In [22]:
corp_wind_df[(corp_wind_df.filter(regex='percent_').values > 100).any(axis=1)]
# corp_wind_df.to_csv('./corp_wind/en_iate_f1_.csv')

,Patterns,percent_ann_xlnet_htfl.pkl,percent_ann_xlnet_wind.pkl,percent_ann_xlnet_equi.pkl,percent_ann_xlnet_corp.pkl,percent_nes_xlnet_htfl.pkl,percent_nes_xlnet_wind.pkl,percent_nes_xlnet_equi.pkl,percent_nes_xlnet_corp.pkl
1,ADJ_NOUN_F1,104.65,98.11,96.61,97.18,102.49,98.92,97.59,99.45
3,ADJ_ADJ_NOUN_F1,101.01,99.47,99.63,99.11,100.54,99.31,99.75,99.07
5,NOUN_ADJ_NOUN_F1,100.11,99.28,99.80,99.41,99.95,99.31,99.75,99.55
6,NOUN_NOUN_NOUN_F1,99.95,99.45,99.77,99.59,100.32,99.31,99.88,99.75
13,NOUN_PRON_F1,100.22,98.31,99.40,99.78,100.20,98.95,99.70,99.81
14,ADJ_NOUN_ADJ_NOUN_F1,99.97,99.98,99.97,99.96,100.05,99.93,99.98,99.96

In [21]:
equi_wind = pd.read_csv('./equi_wind/en_iate_f1.csv').rename(columns={'Unnamed: 0':'Patterns'})
equi_wind = equi_wind[equi_wind['Patterns'].str.endswith('_F1')]
for col in cols:
    equi_wind['percent_'+col] = round(equi_wind[col]*100/equi_wind[col].iloc[0],2)
equi_wind_df = equi_wind.filter(regex='percent_|Patterns')
equi_wind_df.to_csv('./equi_wind/en_iate_f1_.csv')

In [11]:
equi_wind_df[(equi_wind_df.filter(regex='percent_').values > 100).any(axis=1)]

,Patterns,percent_ann_xlnet_htfl.pkl,percent_ann_xlnet_wind.pkl,percent_ann_xlnet_equi.pkl,percent_ann_xlnet_corp.pkl,percent_nes_xlnet_htfl.pkl,percent_nes_xlnet_wind.pkl,percent_nes_xlnet_equi.pkl,percent_nes_xlnet_corp.pkl
1,ADJ_NOUN_F1,106.27,97.59,90.84,113.66,105.04,98.64,91.98,100.35
2,NOUN_NOUN_F1,103.82,80.80,90.03,105.33,99.40,87.02,91.08,92.08
3,ADJ_ADJ_NOUN_F1,101.71,99.43,98.70,99.91,101.09,99.60,98.93,100.00
4,ADJ_NOUN_NOUN_F1,100.52,98.78,98.80,102.90,99.78,98.93,99.19,100.79
5,NOUN_ADJ_NOUN_F1,100.26,98.83,99.37,99.81,100.08,99.33,99.47,100.00
6,NOUN_NOUN_NOUN_F1,99.77,98.67,99.37,102.71,99.86,99.15,99.68,100.35
13,NOUN_PRON_F1,100.26,98.15,99.21,99.53,100.14,98.95,99.77,99.85

In [ ]:
 = pd.read_csv('./equi_wind/en_iate_f1.csv')